services:

  mysql:
    image: mariadb:12.3
    ports:
      - "13341:3306"
    environment:
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: laravel
      MARIADB_ROOT_PASSWORD: root123
      TZ: "Europe/Amsterdam"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: build/docker/php/Dockerfile
      target: dev
    depends_on:
      - mysql
    environment:
      HOME: /tmp # To give artisan tinker a writable home directory
    volumes:
      - ./:/var/www/html:delegated

  nginx:
    build:
      context: .
      dockerfile: build/docker/nginx/Dockerfile
    depends_on:
      - app
    networks:
        - default
        - rocva-proxy
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=rocva-proxy"
        - "traefik.http.routers.devops-advanced.rule=Host(`devops-advanced.localhost`)"
        - "traefik.http.routers.devops-advanced.entrypoints=web"
        - "traefik.http.services.devops-advanced.loadbalancer.server.port=80"
    volumes:
      - ./public:/var/www/html/public:ro

networks:
    rocva-proxy:
        external: true
        name: rocva-proxy

volumes:
    db-data: ~
